name: Build Alpine qcow2 (rootless)

on:
  workflow_dispatch:

jobs:
  build-qcow2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libguestfs-tools wget

      - name: Download Alpine minirootfs
        run: |
          wget https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-3.22.0-x86_64.tar.gz -O alpine-minirootfs.tar.gz
          mkdir rootfs
          tar -xpf alpine-minirootfs.tar.gz -C rootfs

      - name: Create qcow2 from rootfs
        run: |
          virt-make-fs --format=qcow2 --type=ext4 rootfs alpine.qcow2

      - name: Upload qcow2 artifact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-rootless-qcow2
          path: alpine.qcow2
