name: Build Alpine QEMU Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Installer QEMU et utilitaires
        run: |
          brew install qemu
          apt install libguestfs-tools

      - name: Construire l'image Alpine
        run: bash scripts/build_alpine.sh

      - name: Vérifier l'image
        run: ls -lh alpine-amd64-docker.qcow2

      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: alpine-qemu-image
          path: alpine-amd64-docker.qcow2
